---
title: Turtle snowflakes
hero_image: images/banner.png
description: Write code to draw snowflakes with Python Turtle
original_url: https://raspberrypi.org/learning/turtle-snowflakes
theme: navy
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 2, disseny-0, programació-2, phys-comp-0, fabricació-0, comunitat-0
interests: art
technologies: python
site_areas: projectes
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducció
  - 
    title: Què necessitaràs
  - 
    title: How to draw with Python Turtle
  - 
    title: How to turn with Python Turtle
  - 
    title: Using loops to create shapes
  - 
    title: Creating spiral patterns
  - 
    title: Changing the pen colour randomly
  - 
    title: Using a function to draw a snowflake
  - 
    title: "Challenge: every snowflake is different"
