---
title: Turtle snowflakes
hero_image: images / banner.png
description: Write code to draw snowflakes with Python Turtle
original_url: https://raspberrypi.org/learning/turtle-snowflakes
theme: 해군
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 2, 디자인 -0, 프로그래밍 -2, phys-comp-0, 제조 -0, 커뮤니티 -0
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: 소개
  - 
    title: 준비물
  - 
    title: How to draw with Python Turtle
  - 
    title: How to turn with Python Turtle
  - 
    title: Using loops to create shapes
  - 
    title: Creating spiral patterns
  - 
    title: Changing the pen colour randomly
  - 
    title: Using a function to draw a snowflake
  - 
    title: "Challenge: every snowflake is different"
